app = "ultradag-node-3"
primary_region = "ams"

[build]

[env]
  RUST_LOG = "info"
  PORT = "9333"
  RPC_PORT = "10333"
  DATA_DIR = "/data"
  VALIDATORS = "4"
  SEED = "206.51.242.223:9333 137.66.57.226:9333 169.155.55.151:9333"
  NO_BOOTSTRAP = "true"
  CLEAN_STATE = "true"

[mounts]
  source = "ultradag_data"
  destination = "/data"

[http_service]
  internal_port = 10333
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "120s"
    interval = "30s"
    method = "GET"
    path = "/status"
    timeout = "10s"

[[services]]
  internal_port = 9333
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 9333

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "60s"

